// LOCALHOST
 
### Get all contacts
GET http://localhost:8080/spanishSpeaking

### Get contacts by id
GET http://localhost:8080/spanishSpeaking/65c59da09179c5681fb08bab

# GET http://localhost:8080/spanishSpeaking/65c59da09179c5681fb08bac
# GET http://localhost:8080/spanishSpeaking/65c59da09179c5681fb08bad
# GET http://localhost:8080/spanishSpeaking/65c59da09179c5681fb08bae
# GET http://localhost:8080/spanishSpeaking/65c59da09179c5681fb08baf
# GET http://localhost:8080/spanishSpeaking/65c59da09179c5681fb08bb0
# GET http://localhost:8080/spanishSpeaking/65c59da09179c5681fb08bb1
# GET http://localhost:8080/spanishSpeaking/65c59da09179c5681fb08bb2
# GET http://localhost:8080/spanishSpeaking/65c59da09179c5681fb08bb3
# GET http://localhost:8080/spanishSpeaking/65c59da09179c5681fb08bb4

### Create contact
POST http://localhost:8080/spanishSpeaking/ HTTP/1.1
Content-Type: application/json

{
      "countryName": "Honduras",
      "flag": "HN",
      "capital": "Tegucigalpa",
      "population": "9,450,711",
      "percentNativeSpeakers": "98.70%"
},


###PUT contact
PUT http://localhost:8080/spanishSpeaking/65b566e902f3f3feeb88e382 HTTP/1.1
Content-Type: application/json

{
    "countryName": "Guatemala",
    "flag": "GT",
    "capital": "Guatemala City",
    "population": "10,555,746",
    "percentNativeSpeakers": "89.50%"
}

###DELETE contact
DELETE http://localhost:8080/spanishSpeaking/65b566e902f3f3feeb88e383 HTTP/1.1


### PRODUCTION Deploy 
GET https://ws5-spanishspeakingapi.onrender.com

###Get single
GET https://ws5-spanishspeakingapi.onrender.com/65c59da09179c5681fb08bab
GET https://ws5-spanishspeakingapi.onrender.com/65c59da09179c5681fb08bac
GET https://ws5-spanishspeakingapi.onrender.com/65c59da09179c5681fb08bad
GET https://ws5-spanishspeakingapi.onrender.com/65c59da09179c5681fb08bae
GET https://ws5-spanishspeakingapi.onrender.com/65c59da09179c5681fb08baf
GET https://ws5-spanishspeakingapi.onrender.com/65c59da09179c5681fb08bb0
GET https://ws5-spanishspeakingapi.onrender.com/65c59da09179c5681fb08bb1
GET https://ws5-spanishspeakingapi.onrender.com/65c59da09179c5681fb08bb2
GET https://ws5-spanishspeakingapi.onrender.com/65c59da09179c5681fb08bb3
GET https://ws5-spanishspeakingapi.onrender.com/65c59da09179c5681fb08bb4

### Create contact
POST https://ws5-spanishspeakingapi.onrender.com/spanishSpeaking HTTP/1.1
Content-Type: application/json

{
      "countryName": "Honduras",
      "flag": "HN",
      "capital": "Tegucigalpa",
      "population": "9,450,711",
      "percentNativeSpeakers": "98.70%"
}

###PUT contact
PUT https://ws5-spanishspeakingapi.onrender.com/spanishSpeaking/65c59da09179c5681fb08bb4 HTTP/1.1
Content-Type: application/json

{
      "countryName": "Guatemala",
      "flag": "GT",
      "capital": "Guatemala City",
      "population": "10,555,746",
      "percentNativeSpeakers": "89.50%"
}

###DELETE contact
DELETE https://ws5-spanishspeakingapi.onrender.com/spanishSpeaking/65c59da09179c5681fb08bab HTTP/1.1
